\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{}
  \pretitle{\vspace{\droptitle}}
  \posttitle{}
  \author{}
  \preauthor{}\postauthor{}
  \date{}
  \predate{}\postdate{}


\begin{document}

\hypertarget{analise-de-vinhos-tintos}{%
\section{Análise de Vinhos Tintos}\label{analise-de-vinhos-tintos}}

\hypertarget{por-ricardo-lino}{%
\section{\#\# por Ricardo Lino}\label{por-ricardo-lino}}

\begin{quote}
Descrição do Conjunto de Dados escolhido: Este conjunto de dados contém
1.599 vinhos tintos com 11 variáveis de propriedades químicas do vinho.
Ao menos 3 especialistas em vinhos avaliaram cada vinho, fornecendo uma
nota entre 0 (muito ruim) e 10 (muito excelente).
\end{quote}

Questão Guia: Quais propriedades químicas influenciam a qualidade dos
vinhos tintos?

origem:
``\url{https://s3.amazonaws.com/udacity-hosted-downloads/ud651/wineQualityInfo.txt}''

Author: P. Cortez, A. Cerdeira, F. Almeida, T. Matos and J. Reis.
Modeling wine preferences by data mining from physicochemical
properties. In Decision Support Systems, Elsevier, 47(4):547-553. ISSN:
0167-9236.

\begin{verbatim}
## [1] "Dimensão dos dados:"
\end{verbatim}

\begin{verbatim}
## [1] 1599   13
\end{verbatim}

\begin{verbatim}
## [1] "Estrutura dos Dados:"
\end{verbatim}

\begin{verbatim}
## 'data.frame':    1599 obs. of  13 variables:
##  $ X                   : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ fixed.acidity       : num  7.4 7.8 7.8 11.2 7.4 7.4 7.9 7.3 7.8 7.5 ...
##  $ volatile.acidity    : num  0.7 0.88 0.76 0.28 0.7 0.66 0.6 0.65 0.58 0.5 ...
##  $ citric.acid         : num  0 0 0.04 0.56 0 0 0.06 0 0.02 0.36 ...
##  $ residual.sugar      : num  1.9 2.6 2.3 1.9 1.9 1.8 1.6 1.2 2 6.1 ...
##  $ chlorides           : num  0.076 0.098 0.092 0.075 0.076 0.075 0.069 0.065 0.073 0.071 ...
##  $ free.sulfur.dioxide : num  11 25 15 17 11 13 15 15 9 17 ...
##  $ total.sulfur.dioxide: num  34 67 54 60 34 40 59 21 18 102 ...
##  $ density             : num  0.998 0.997 0.997 0.998 0.998 ...
##  $ pH                  : num  3.51 3.2 3.26 3.16 3.51 3.51 3.3 3.39 3.36 3.35 ...
##  $ sulphates           : num  0.56 0.68 0.65 0.58 0.56 0.56 0.46 0.47 0.57 0.8 ...
##  $ alcohol             : num  9.4 9.8 9.8 9.8 9.4 9.4 9.4 10 9.5 10.5 ...
##  $ quality             : int  5 5 5 6 5 5 5 7 7 5 ...
\end{verbatim}

\begin{verbatim}
## [1] "Sumário dos Dados:"
\end{verbatim}

\begin{verbatim}
##        X          fixed.acidity   volatile.acidity  citric.acid   
##  Min.   :   1.0   Min.   : 4.60   Min.   :0.1200   Min.   :0.000  
##  1st Qu.: 400.5   1st Qu.: 7.10   1st Qu.:0.3900   1st Qu.:0.090  
##  Median : 800.0   Median : 7.90   Median :0.5200   Median :0.260  
##  Mean   : 800.0   Mean   : 8.32   Mean   :0.5278   Mean   :0.271  
##  3rd Qu.:1199.5   3rd Qu.: 9.20   3rd Qu.:0.6400   3rd Qu.:0.420  
##  Max.   :1599.0   Max.   :15.90   Max.   :1.5800   Max.   :1.000  
##  residual.sugar     chlorides       free.sulfur.dioxide
##  Min.   : 0.900   Min.   :0.01200   Min.   : 1.00      
##  1st Qu.: 1.900   1st Qu.:0.07000   1st Qu.: 7.00      
##  Median : 2.200   Median :0.07900   Median :14.00      
##  Mean   : 2.539   Mean   :0.08747   Mean   :15.87      
##  3rd Qu.: 2.600   3rd Qu.:0.09000   3rd Qu.:21.00      
##  Max.   :15.500   Max.   :0.61100   Max.   :72.00      
##  total.sulfur.dioxide    density             pH          sulphates     
##  Min.   :  6.00       Min.   :0.9901   Min.   :2.740   Min.   :0.3300  
##  1st Qu.: 22.00       1st Qu.:0.9956   1st Qu.:3.210   1st Qu.:0.5500  
##  Median : 38.00       Median :0.9968   Median :3.310   Median :0.6200  
##  Mean   : 46.47       Mean   :0.9967   Mean   :3.311   Mean   :0.6581  
##  3rd Qu.: 62.00       3rd Qu.:0.9978   3rd Qu.:3.400   3rd Qu.:0.7300  
##  Max.   :289.00       Max.   :1.0037   Max.   :4.010   Max.   :2.0000  
##     alcohol         quality     
##  Min.   : 8.40   Min.   :3.000  
##  1st Qu.: 9.50   1st Qu.:5.000  
##  Median :10.20   Median :6.000  
##  Mean   :10.42   Mean   :5.636  
##  3rd Qu.:11.10   3rd Qu.:6.000  
##  Max.   :14.90   Max.   :8.000
\end{verbatim}

\hypertarget{informacoes-dos-atributos-em-ingles}{%
\section{Informações dos Atributos (em
Inglês)}\label{informacoes-dos-atributos-em-ingles}}

1 - fixed acidity - acidos não volateis presentes no vinho. 2 - volatile
acidity - a quantidade de acido acetico, que em grau elevado pode levar
a um sabor não agradavel (gosto de vinagre). 3 - citric acid -
encontrado em pequenas quantidade pode dar leveza e sabor ao vinhuo. 4 -
residual sugar - o açucar encontrado no vinho após o final da
fermentação. Raro encontrar vinhos com menos de 1 grama por litro.
Vinhos com mais d 45 gramas por litro são considerados doces. 5 -
chlorides - a quantidade de sal no vinho. 6 - free sulfur dioxide -
dióxido de enxofre livre no vinho. Previne a oxidação do vinho a a
proliferação de microorganismos. 7 - total sulfur dioxide - total de
dióxido de enxofre no vinho. Concentraçãoes acima de 50 ppm se tornam
evidente ao cheirar e provar o vinho. 8 - density - densidade do vinho.
9 - pH - nivel de acidez do vinho, de 0 a muito ácido até 14 muito
básico. A maioria dos vinhos esta numa faixa entre 3-4 na escala de ph.
10 - sulphates - um aditivo ao vinho que contribui para preservar o
vinho. 11 - alcohol - \% de alcool no vinho Output variable (based on
sensory data): Quality (score between 0 and 10) - qualidade do vinho de
0 a 10.

\hypertarget{secao-de-graficos-univariados}{%
\section{Seção de Gráficos
Univariados}\label{secao-de-graficos-univariados}}

\hypertarget{qualidade-do-vinho}{%
\subsection{Qualidade do Vinho}\label{qualidade-do-vinho}}

\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/Quality-1.pdf}

\begin{verbatim}
## 
##   3   4   5   6   7   8 
##  10  53 681 638 199  18
\end{verbatim}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   3.000   5.000   6.000   5.636   6.000   8.000
\end{verbatim}

Observações: Uma aproximação de uma curva normal assimetrica, com
skewness negativo.

\hypertarget{secao-de-graficos-univariados}{%
\subsection{SEÇÂO DE GRÀFICOS
UNIVARIADOS}\label{secao-de-graficos-univariados}}

Primeiro vamos dar uma olhada geral na distribuição das variaveis do
nosso data set. Assim podemos conhecer melhor o que temos e direcionar
nossa analise
\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/unnamed-chunk-2-1.pdf}
\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/unnamed-chunk-2-2.pdf}
\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/unnamed-chunk-2-3.pdf}
\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/unnamed-chunk-2-4.pdf}
\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/unnamed-chunk-2-5.pdf}
\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/unnamed-chunk-2-6.pdf}
\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/unnamed-chunk-2-7.pdf}
\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/unnamed-chunk-2-8.pdf}
\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/unnamed-chunk-2-9.pdf}
\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/unnamed-chunk-2-10.pdf}
\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/unnamed-chunk-2-11.pdf}
\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/unnamed-chunk-2-12.pdf}
\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/unnamed-chunk-2-13.pdf}

\hypertarget{criacao-de-uma-nova-variavel-categorica}{%
\subsection{Criação de uma nova variável
categorica}\label{criacao-de-uma-nova-variavel-categorica}}

Como me interessou ver o que influencia na classificacao de um vinho
bom. Pensei em analisar o que diferencia um vinho bom da media, e tab o
que diferencia um vinho ruim. Agrupei classificando os vinhos em LOW,
AVG e TOP. Com base no summario de dados de qualidade, vamos pegar os
vinho com menor qualidade do 1o quantil e maior classificação do que o
3o quantil e classifica-los.

\begin{verbatim}
## 
##  LOW  AVG  TOP 
##   63 1319  217
\end{verbatim}

Sabemos que a classificação de um vinho leva em conta também o fator
preço, que não temos no nosso dataset, por isso temos de tomar cuidado,
as vezes um bom vinho em um preço não é um bom vinho a um nivel de preço
mais alto. Mas mesmo assim vamos continuar nossa analise e escolher
alguma variaveis para nosso estudo.

\hypertarget{acidos-e-acidez-dos-vinhos}{%
\subsection{1- Acidos e acidez dos
Vinhos}\label{acidos-e-acidez-dos-vinhos}}

\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/Variavies.1-1.pdf}
Ácidex Fixa -\textgreater{} Maior concentração maior a qualidade

\begin{verbatim}
## # A tibble: 3 x 4
##   quality.group  Mean Median DevPad
##   <fct>         <dbl>  <dbl>  <dbl>
## 1 LOW            7.87   7.50   1.65
## 2 AVG            8.25   7.80   1.68
## 3 TOP            8.85   8.70   2.00
\end{verbatim}

Ácidex Volatil -\textgreater{} Menor concentração maior a qualidade

\begin{verbatim}
## # A tibble: 3 x 4
##   quality.group  Mean Median DevPad
##   <fct>         <dbl>  <dbl>  <dbl>
## 1 LOW           0.724  0.680  0.248
## 2 AVG           0.539  0.540  0.168
## 3 TOP           0.406  0.370  0.145
\end{verbatim}

Ácido Cítrico -\textgreater{} Maior concentração maior a qualidade

\begin{verbatim}
## # A tibble: 3 x 4
##   quality.group  Mean Median DevPad
##   <fct>         <dbl>  <dbl>  <dbl>
## 1 LOW           0.174 0.0800  0.207
## 2 AVG           0.258 0.240   0.188
## 3 TOP           0.376 0.400   0.194
\end{verbatim}

\hypertarget{chloridios-e-dioxido-de-enxofre-livre-nao-livre-nova-variavel-e-total}{%
\subsection{2- Chloridios e Dioxido de Enxofre livre, não livre (nova
variavel) e
total}\label{chloridios-e-dioxido-de-enxofre-livre-nao-livre-nova-variavel-e-total}}

Ajustei os limites dos gráficos pois tinham muitos outliers

\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/Variavies.2-1.pdf}
Açucar residaul -\textgreater{} Parece que é uma caracteristica que não
é bem definida. Se analisarmos as mulheres e os homens tem gostos
diferentes o que pode ter afetado a classificação de qualidade (mulheres
tendem a gostar mais de vinhos mais doces, mas é uma especulação).
Podemos refazer a analise tirando os outliers.

\begin{verbatim}
## # A tibble: 3 x 4
##   quality.group  Mean Median DevPad
##   <fct>         <dbl>  <dbl>  <dbl>
## 1 LOW            2.68   2.10   1.72
## 2 AVG            2.50   2.20   1.40
## 3 TOP            2.71   2.30   1.36
\end{verbatim}

Clorideos -\textgreater{} Menor concentração caracteristica dos vinhos
de melhor qualidade

\begin{verbatim}
## # A tibble: 3 x 4
##   quality.group   Mean Median DevPad
##   <fct>          <dbl>  <dbl>  <dbl>
## 1 LOW           0.0957 0.0800 0.0751
## 2 AVG           0.0890 0.0800 0.0475
## 3 TOP           0.0759 0.0730 0.0285
\end{verbatim}

\hypertarget{concentracoes-de-dioxido-de-enxofre-e-sulphatos.}{%
\subsection{3 - Concentrações de Dioxido de enxofre e
sulphatos.}\label{concentracoes-de-dioxido-de-enxofre-e-sulphatos.}}

\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/Variavies.3-1.pdf}

Dioxido de Enxofre Livre (free.sulfur.dioxide) -\textgreater{} Sem muito
a nos dizer.

\begin{verbatim}
## # A tibble: 3 x 4
##   quality.group  Mean Median DevPad
##   <fct>         <dbl>  <dbl>  <dbl>
## 1 LOW            12.1     9.   9.08
## 2 AVG            16.4    14.  10.5 
## 3 TOP            14.0    11.  10.2
\end{verbatim}

Dioxido de Enxofre Total (free.sulfur.dioxide) -\textgreater{} Sem muito
a nos dizer.

\begin{verbatim}
## # A tibble: 3 x 4
##   quality.group  Mean Median DevPad
##   <fct>         <dbl>  <dbl>  <dbl>
## 1 LOW            34.4    26.   26.4
## 2 AVG            48.9    40.   32.7
## 3 TOP            34.9    27.   32.6
\end{verbatim}

Sulfitos (sulphates) -\textgreater{} Já os sulfatos tem muito a nos
dizer. Quanto maior a concetração na média melhor qualificado o vinho.

\begin{verbatim}
## # A tibble: 3 x 4
##   quality.group  Mean Median DevPad
##   <fct>         <dbl>  <dbl>  <dbl>
## 1 LOW           0.592  0.560  0.224
## 2 AVG           0.647  0.610  0.167
## 3 TOP           0.743  0.740  0.134
\end{verbatim}

Nesse grupo teve destaque os sulphates, uma maior concetração em vinhos
melhores. Em relação ou dioxido de enxofre vemos um outlier nos vinhos
melhores, mas olhando o grafico vemos que como os outros grupos não tem
tanta relevancia na qualidade.

\hypertarget{densidade-ph-e-nivel-de-alcool}{%
\subsection{4- Densidade, pH e nivel de
Alcool}\label{densidade-ph-e-nivel-de-alcool}}

\includegraphics{Analise_Vinhos_Tintos_files/figure-latex/Variavies.4-1.pdf}
Densidade (density) -\textgreater{} Sem muito a nos dizer a primeira
vista.

\begin{verbatim}
## # A tibble: 3 x 4
##   quality.group  Mean Median  DevPad
##   <fct>         <dbl>  <dbl>   <dbl>
## 1 LOW           0.997  0.997 0.00167
## 2 AVG           0.997  0.997 0.00182
## 3 TOP           0.996  0.996 0.00220
\end{verbatim}

Escala pH (pH) -\textgreater{} Vinhos com PH mais baixo, ou seja com
maior acidez parecem ser melhores na média.

\begin{verbatim}
## # A tibble: 3 x 4
##   quality.group  Mean Median DevPad
##   <fct>         <dbl>  <dbl>  <dbl>
## 1 LOW            3.38   3.38  0.175
## 2 AVG            3.31   3.31  0.152
## 3 TOP            3.29   3.27  0.154
\end{verbatim}

Nível alcoolico (alcohol) -\textgreater{} Vinhos com nível de alcool
maior são melhor classificados.

\begin{verbatim}
## # A tibble: 3 x 4
##   quality.group  Mean Median DevPad
##   <fct>         <dbl>  <dbl>  <dbl>
## 1 LOW            10.2   10.0  0.918
## 2 AVG            10.3   10.0  0.972
## 3 TOP            11.5   11.6  0.998
\end{verbatim}

Podemos pelos gráficos notar que a densidade não parece influenciar
muito (de forma direta), que o PH dos melhores vinhos é na media
ligeriamente mais acido. Em relação ao nível de alcool os vinhos
melhores tem nitidamente uma quantidade maior.

\hypertarget{analise-univariada}{%
\section{Análise Univariada}\label{analise-univariada}}

\hypertarget{qual-a-estrutura-do-conjunto-de-dados}{%
\subsection{Qual a estrutura do conjunto de
Dados?}\label{qual-a-estrutura-do-conjunto-de-dados}}

Existem 1599 vinhos no nosso \emph{dataset} com um índice (X) e com 11
atributos e um \emph{output} quality. Adcionei um agrupamento por nível
de qualidade para poder destacar caracteristicas mais marcantes nos
vinho de baixa, media e alta qualidade. A maioria dos vinho, 1319 foram
classificados como médios \emph{AVG}, 63 (4\%) como de baixa qualidade
\emph{LOW} e 217 (13,6\%) como de alta qualidade \emph{TOP}. LOW
\textbar{} AVG \textbar{} TOP ----\textbar{}------\textbar{}---- 63
\textbar{} 1319 \textbar{} 217

Outras observaçães. - A distribuição da qualidade dos vinhos se aproxima
de uma normal com skew positivo -

\hypertarget{quais-outros-atributos-voce-acha-que-podem-lhe-auxiliar-na-investigacao-destes-atributos-de-interesse}{%
\subsubsection{Quais outros atributos você acha que podem lhe auxiliar
na investigação destes atributos de
interesse?}\label{quais-outros-atributos-voce-acha-que-podem-lhe-auxiliar-na-investigacao-destes-atributos-de-interesse}}

\hypertarget{voce-criou-novas-variaveis-a-partir-dos-atributos-existentes-no-conjunto-de-dados}{%
\subsubsection{Você criou novas variáveis a partir dos atributos
existentes no conjunto de
dados?}\label{voce-criou-novas-variaveis-a-partir-dos-atributos-existentes-no-conjunto-de-dados}}

\hypertarget{dos-atributos-investigados-distribuiaaes-incomuns-foram-encontradas-voce-aplicou-operaaaes-nos-dados-para-limpa-los-ajusta-los-ou-mudar-a-forma-dos-dados-se-sim-por-que}{%
\subsubsection{Dos atributos investigados, distribuiÃ§Ãµes incomuns
foram encontradas? Você aplicou operaÃ§Ãµes nos dados para limpá-los,
ajustá-los ou mudar a forma dos dados? Se sim, por
quê?}\label{dos-atributos-investigados-distribuiaaes-incomuns-foram-encontradas-voce-aplicou-operaaaes-nos-dados-para-limpa-los-ajusta-los-ou-mudar-a-forma-dos-dados-se-sim-por-que}}

\hypertarget{secao-de-graficos-bivariados}{%
\section{Seção de Gráficos
Bivariados}\label{secao-de-graficos-bivariados}}

\hypertarget{analise-bivariada}{%
\section{Análise Bivariada}\label{analise-bivariada}}

\hypertarget{discuta-sobre-alguns-dos-relacionamentos-observados-nesta-parte-da-investigacao.-como-os-atributos-de-interesse-variaram-no-conjunto-de-dados}{%
\subsubsection{Discuta sobre alguns dos relacionamentos observados nesta
parte da investigação. Como os atributos de interesse variaram no
conjunto de
dados?}\label{discuta-sobre-alguns-dos-relacionamentos-observados-nesta-parte-da-investigacao.-como-os-atributos-de-interesse-variaram-no-conjunto-de-dados}}

\hypertarget{voce-observou-algum-relacionamento-interessante-entre-os-outros-atributos-os-que-nao-sao-de-interesse}{%
\subsubsection{Você observou algum relacionamento interessante entre os
outros atributos (os que não são de
interesse)?}\label{voce-observou-algum-relacionamento-interessante-entre-os-outros-atributos-os-que-nao-sao-de-interesse}}

\hypertarget{qual-foi-o-relacionamento-mais-forte-encontrado}{%
\subsubsection{Qual foi o relacionamento mais forte
encontrado?}\label{qual-foi-o-relacionamento-mais-forte-encontrado}}

\hypertarget{secao-de-graficos-multivariados}{%
\section{Seção de Gráficos
Multivariados}\label{secao-de-graficos-multivariados}}

\hypertarget{analise-multivariada}{%
\section{Análise Multivariada}\label{analise-multivariada}}

\hypertarget{discuta-sobre-os-relacionamentos-observados-nesta-parte-da-investigacao.-quais-atributos-que-fortaleceram-os-demais-na-observacao-das-variaveis-de-interesse}{%
\subsubsection{Discuta sobre os relacionamentos observados nesta parte
da investigação. Quais atributos que fortaleceram os demais na
observação das variáveis de
interesse?}\label{discuta-sobre-os-relacionamentos-observados-nesta-parte-da-investigacao.-quais-atributos-que-fortaleceram-os-demais-na-observacao-das-variaveis-de-interesse}}

\hypertarget{interaaaes-surpreendentes-eou-interessantes-foram-encontradas-entre-os-atributos}{%
\subsubsection{InteraÃ§Ãµes surpreendentes e/ou interessantes foram
encontradas entre os
atributos?}\label{interaaaes-surpreendentes-eou-interessantes-foram-encontradas-entre-os-atributos}}

\hypertarget{opcional-modelos-foram-criados-usando-este-conjunto-de-dados-discuta-sobre-os-pontos-fortes-e-as-limitaaaes-do-seu-modelo.}{%
\subsubsection{OPCIONAL: Modelos foram criados usando este conjunto de
dados? Discuta sobre os pontos fortes e as limitaÃ§Ãµes do seu
modelo.}\label{opcional-modelos-foram-criados-usando-este-conjunto-de-dados-discuta-sobre-os-pontos-fortes-e-as-limitaaaes-do-seu-modelo.}}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{graficos-finais-e-sumario}{%
\section{Gráficos Finais e Sumário}\label{graficos-finais-e-sumario}}

\hypertarget{primeiro-grafico}{%
\subsubsection{Primeiro Gráfico}\label{primeiro-grafico}}

\hypertarget{descricao-do-primeiro-grafico}{%
\subsubsection{Descrição do Primeiro
Gráfico}\label{descricao-do-primeiro-grafico}}

\hypertarget{segundo-grafico}{%
\subsubsection{Segundo Gráfico}\label{segundo-grafico}}

\hypertarget{descricao-do-segundo-grafico}{%
\subsubsection{Descrição do Segundo
Gráfico}\label{descricao-do-segundo-grafico}}

\hypertarget{terceiro-grafico}{%
\subsubsection{Terceiro Gráfico}\label{terceiro-grafico}}

\hypertarget{descricao-do-terceiro-grafico}{%
\subsubsection{Descrição do Terceiro
Gráfico}\label{descricao-do-terceiro-grafico}}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{reflexao}{%
\section{Reflexão}\label{reflexao}}


\end{document}
